# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Kaíque Machado
# Description of the Site
description: Engenheiro de Computação
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Kaíque Machado, Engenheiro, Computação
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/meta.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kaique.eng.br@gmail.com
facebook_username: 
twitter_username: 
instagram_username: kaique.eng.br
linkedin_username: kaiquecodes
github_username:  kaiquecodes
youtube_channel_id: UC1831hqdPeCBrrp17zMf3Ag
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Kaíque Machado
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/kaiquecodes/kaiquecodes.github.io/master/assets/images/profile.jpg
# 60 Words About the Author
author-about: Olá Mundo! Sou o Kaíque Machado, nasci em Recife, Pernambuco. Sou Engenheiro de Computação pela Universidade Federal do Rio Grande do Norte (UFRN) e especialista em desenvolvimento de software pelo Instituto Metrópole Digital (UFRN) em parceria com o Tribunal Regional Federal da 5º Região (TRF5). Nesta página, você vai encontrar meus artigos, meus projetos pessoais, meu currículo e a minha música favorita para animar. Todos os links estão logo abaixo.
 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.kaique.eng.br/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
