# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Kaíque Machado
# Description of the Site
description: Estudante de Engenharia de Computação e Residente em T.I.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/kaiquecodes/teste/main/meta.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kaique.engcomp@gmail.com
facebook_username: 
twitter_username: 
instagram_username: kaiquecodes
linkedin_username: kaiquecodes
github_username:  kaiquecodes
youtube_channel_id: UC1831hqdPeCBrrp17zMf3Ag
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 	z10zb1kcoakpz2lmdrb88rloq

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Kaiquecodes
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/kaiquecodes/kaiquecodes.github.io/master/assets/images/profile.jpg
# 60 Words About the Author
author-about: Olá Mundo! Sou o Kaíque Machado, nasci em Recife, Pernambuco. Estou sempre em busca de novos conhecimentos, por isso, além do estudo da Engenharia, procuro conhecer mais sobre outros campos do saber como a Música e a História. A Música porque sem ela a vida seria um erro, a História para entender como chegamos até aqui, e a Engenharia para projetar nosso futuro. Além disso, meu tempo é dedicado a estar com minha família, amigos, pets, músicas, livros e a guitarra.  Nesta página, você vai encontrar alguns artigos sobre meus estudos, alguns projetos pessoais, meu currículo e uma playlist para animar. Todos os links estão logo abaixo.
 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/kaiquecodes

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
